#
# Makefile
#

all: clean hellow_client hellow_server

hellow_client:
	gcc -o hellow_client hellow_client.cc
hellow_server:
	gcc -o hellow_server hellow_server.cc

clean:
	rm -f hellow_client hellow_server
